"""add_ai_market_analysis_models

Revision ID: 093ca04dc920
Revises: 
Create Date: 2025-11-18 03:39:06.811500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093ca04dc920'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('tickers_mentioned', sa.Text(), nullable=True),
    sa.Column('actions_taken', sa.Text(), nullable=True),
    sa.Column('results_found', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('response_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_queries_created_at'), 'ai_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_queries_id'), 'ai_queries', ['id'], unique=False)
    op.create_index(op.f('ix_ai_queries_user_id'), 'ai_queries', ['user_id'], unique=False)
    op.create_table('market_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_summary', sa.Text(), nullable=True),
    sa.Column('top_movers', sa.Text(), nullable=True),
    sa.Column('sector_performance', sa.Text(), nullable=True),
    sa.Column('pattern_highlights', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('trade_ideas', sa.Text(), nullable=True),
    sa.Column('market_sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('sent_to_telegram', sa.Boolean(), nullable=True),
    sa.Column('telegram_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_briefs_brief_date'), 'market_briefs', ['brief_date'], unique=False)
    op.create_index(op.f('ix_market_briefs_id'), 'market_briefs', ['id'], unique=False)
    op.create_table('scan_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=True),
    sa.Column('tickers_scanned', sa.Integer(), nullable=True),
    sa.Column('patterns_found', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_logs_id'), 'scan_logs', ['id'], unique=False)
    op.create_index(op.f('ix_scan_logs_scan_type'), 'scan_logs', ['scan_type'], unique=False)
    op.create_index(op.f('ix_scan_logs_start_time'), 'scan_logs', ['start_time'], unique=False)
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_id'), 'tickers', ['id'], unique=False)
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    op.create_table('universe_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('universe', sa.String(length=50), nullable=True),
    sa.Column('total_scanned', sa.Integer(), nullable=True),
    sa.Column('patterns_found', sa.Integer(), nullable=True),
    sa.Column('top_score', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universe_scans_id'), 'universe_scans', ['id'], unique=False)
    op.create_index(op.f('ix_universe_scans_scan_date'), 'universe_scans', ['scan_date'], unique=False)
    op.create_index(op.f('ix_universe_scans_universe'), 'universe_scans', ['universe'], unique=False)
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('trigger_price', sa.Float(), nullable=True),
    sa.Column('trigger_value', sa.Float(), nullable=True),
    sa.Column('alert_sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('sent_via', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_alert_sent_at'), 'alert_logs', ['alert_sent_at'], unique=False)
    op.create_index(op.f('ix_alert_logs_alert_type'), 'alert_logs', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_logs_id'), 'alert_logs', ['id'], unique=False)
    op.create_index(op.f('ix_alert_logs_ticker_id'), 'alert_logs', ['ticker_id'], unique=False)
    op.create_index(op.f('ix_alert_logs_user_id'), 'alert_logs', ['user_id'], unique=False)
    op.create_table('market_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('analysis_type', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('analysis_text', sa.Text(), nullable=True),
    sa.Column('support_levels', sa.Text(), nullable=True),
    sa.Column('resistance_levels', sa.Text(), nullable=True),
    sa.Column('trend_direction', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('risk_assessment', sa.Text(), nullable=True),
    sa.Column('trade_ideas', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('chart_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_analysis_analysis_type'), 'market_analysis', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_market_analysis_created_at'), 'market_analysis', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_analysis_id'), 'market_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_market_analysis_ticker_id'), 'market_analysis', ['ticker_id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_scraped_at'), 'news_articles', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_news_articles_ticker_id'), 'news_articles', ['ticker_id'], unique=False)
    op.create_table('pattern_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('pattern_type', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('criteria_met', sa.Text(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('volume_dry_up', sa.Boolean(), nullable=True),
    sa.Column('consolidation_days', sa.Integer(), nullable=True),
    sa.Column('chart_url', sa.Text(), nullable=True),
    sa.Column('rs_rating', sa.Float(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_scans_id'), 'pattern_scans', ['id'], unique=False)
    op.create_index(op.f('ix_pattern_scans_pattern_type'), 'pattern_scans', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_pattern_scans_scanned_at'), 'pattern_scans', ['scanned_at'], unique=False)
    op.create_index(op.f('ix_pattern_scans_ticker_id'), 'pattern_scans', ['ticker_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('target_entry', sa.Float(), nullable=True),
    sa.Column('target_stop', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('alert_threshold', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_added_at'), 'watchlists', ['added_at'], unique=False)
    op.create_index(op.f('ix_watchlists_id'), 'watchlists', ['id'], unique=False)
    op.create_index(op.f('ix_watchlists_status'), 'watchlists', ['status'], unique=False)
    op.create_index(op.f('ix_watchlists_ticker_id'), 'watchlists', ['ticker_id'], unique=False)
    op.create_index(op.f('ix_watchlists_triggered_at'), 'watchlists', ['triggered_at'], unique=False)
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('news_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('impact_assessment', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_sentiment_analyzed_at'), 'news_sentiment', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_news_sentiment_article_id'), 'news_sentiment', ['article_id'], unique=False)
    op.create_index(op.f('ix_news_sentiment_id'), 'news_sentiment', ['id'], unique=False)
    op.create_index(op.f('ix_news_sentiment_sentiment'), 'news_sentiment', ['sentiment'], unique=False)
    op.create_index(op.f('ix_news_sentiment_ticker_id'), 'news_sentiment', ['ticker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_sentiment_ticker_id'), table_name='news_sentiment')
    op.drop_index(op.f('ix_news_sentiment_sentiment'), table_name='news_sentiment')
    op.drop_index(op.f('ix_news_sentiment_id'), table_name='news_sentiment')
    op.drop_index(op.f('ix_news_sentiment_article_id'), table_name='news_sentiment')
    op.drop_index(op.f('ix_news_sentiment_analyzed_at'), table_name='news_sentiment')
    op.drop_table('news_sentiment')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_triggered_at'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_ticker_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_status'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_added_at'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_pattern_scans_ticker_id'), table_name='pattern_scans')
    op.drop_index(op.f('ix_pattern_scans_scanned_at'), table_name='pattern_scans')
    op.drop_index(op.f('ix_pattern_scans_pattern_type'), table_name='pattern_scans')
    op.drop_index(op.f('ix_pattern_scans_id'), table_name='pattern_scans')
    op.drop_table('pattern_scans')
    op.drop_index(op.f('ix_news_articles_ticker_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_scraped_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_market_analysis_ticker_id'), table_name='market_analysis')
    op.drop_index(op.f('ix_market_analysis_id'), table_name='market_analysis')
    op.drop_index(op.f('ix_market_analysis_created_at'), table_name='market_analysis')
    op.drop_index(op.f('ix_market_analysis_analysis_type'), table_name='market_analysis')
    op.drop_table('market_analysis')
    op.drop_index(op.f('ix_alert_logs_user_id'), table_name='alert_logs')
    op.drop_index(op.f('ix_alert_logs_ticker_id'), table_name='alert_logs')
    op.drop_index(op.f('ix_alert_logs_id'), table_name='alert_logs')
    op.drop_index(op.f('ix_alert_logs_alert_type'), table_name='alert_logs')
    op.drop_index(op.f('ix_alert_logs_alert_sent_at'), table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index(op.f('ix_universe_scans_universe'), table_name='universe_scans')
    op.drop_index(op.f('ix_universe_scans_scan_date'), table_name='universe_scans')
    op.drop_index(op.f('ix_universe_scans_id'), table_name='universe_scans')
    op.drop_table('universe_scans')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_id'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_scan_logs_start_time'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_scan_type'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_id'), table_name='scan_logs')
    op.drop_table('scan_logs')
    op.drop_index(op.f('ix_market_briefs_id'), table_name='market_briefs')
    op.drop_index(op.f('ix_market_briefs_brief_date'), table_name='market_briefs')
    op.drop_table('market_briefs')
    op.drop_index(op.f('ix_ai_queries_user_id'), table_name='ai_queries')
    op.drop_index(op.f('ix_ai_queries_id'), table_name='ai_queries')
    op.drop_index(op.f('ix_ai_queries_created_at'), table_name='ai_queries')
    op.drop_table('ai_queries')
    # ### end Alembic commands ###
